# https://github.com/paritytech/substrate/blob/master/rustfmt.toml
# Basic
hard_tabs = true
max_width = 120
tab_spaces = 2
use_small_heuristics = "Max"
attributes.first_last_attr_on_same_line = true
# Imports
imports_granularity = "Crate"
reorder_imports = true
# Consistency
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
# Misc
chain_width = 90
spaces_around_ranges = false
binop_separator = "Back"
reorder_impl_items = false
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
match_block_trailing_comma = true
trailing_comma = "Never"
trailing_semicolon = false
use_field_init_shorthand = true
struct_lit_style = "Block"
